Repository DeveloperAcademy-POSTECH/MacC-Team-TARS, pull requests merged in 2022-12, with the labels that each got.

#94 [FEAT] Detecting 음원 및 Detecting 됐을 때 음원 재생
  Tars/Tars.xcodeproj/project.pbxproj
  Tars/Tars/SoundAssets/Detecting_planet.wav
  Tars/Tars/SoundManager/SoundManager.swift
  Tars/Tars/ViewController/UniverseSearchViewController.swift
Labels: ✨feature, 🧑‍💻니로, 🔍search, 🧭 explore

#96 [FEAT] add VoiceOver of chapter information
  Tars/Tars/Extensions/Localized.swift
  Tars/Tars/ViewController/InfoViewController.swift
  Tars/en.lproj/Localizable.strings
Labels: ✨feature, 👩‍💻소니

#98 [FEAT] 컨텐츠 로컬라이징
  Tars/Tars/Extensions/Localized.swift
  Tars/Tars/Extensions/PlanetList+Extension.swift
  Tars/en.lproj/Localizable.strings
  Tars/ko.lproj/Localizable.strings
Labels: 👩‍💻제리, 📚 info
