Repository DeveloperAcademy-POSTECH/MacC-Team-TARS, pull requests merged in 2022-10, with the labels that each got.

#3 [FEAT] 3D background 및 guideCircleView 구현
  Tars/Tars.xcodeproj/project.pbxproj
  Tars/Tars/.swiftlint.yml
  Tars/Tars/Assets.xcassets/UniverseBackground/Contents.json
  Tars/Tars/Assets.xcassets/UniverseBackground/sky1.imageset/Contents.json
  Tars/Tars/Assets.xcassets/UniverseBackground/sky1.imageset/sky.jpg
  Tars/Tars/Assets.xcassets/UniverseBackground/sky2.imageset/Contents.json
  Tars/Tars/Assets.xcassets/UniverseBackground/sky2.imageset/sky.jpg
  Tars/Tars/Assets.xcassets/UniverseBackground/sky3.imageset/Contents.json
  Tars/Tars/Assets.xcassets/UniverseBackground/sky3.imageset/sky.jpg
  Tars/Tars/Assets.xcassets/UniverseBackground/sky4.imageset/Contents.json
  Tars/Tars/Assets.xcassets/UniverseBackground/sky4.imageset/sky.jpg
  Tars/Tars/Assets.xcassets/UniverseBackground/sky5.imageset/Contents.json
  Tars/Tars/Assets.xcassets/UniverseBackground/sky5.imageset/sky.jpg
  Tars/Tars/Assets.xcassets/UniverseBackground/sky6.imageset/Contents.json
  Tars/Tars/Assets.xcassets/UniverseBackground/sky6.imageset/sky.jpg
  Tars/Tars/Extensions/Color+Extension.swift
  Tars/Tars/Extensions/CommonVariables+Extension.swift
  Tars/Tars/Extensions/DashedCircle+Extension.swift
  Tars/Tars/Extensions/View+Extension.swift
  Tars/Tars/UniverseBackground.scn
  Tars/Tars/View/CustomCircleView.swift
  Tars/Tars/ViewController/UniverseViewController.swift
Labels: ✨feature, 👩‍💻레나, 🧭 explore

#7 [FIX] SwiftLint의 수정사항에 따라 develop branch 수정
  Tars/Tars/AppDelegate.swift
  Tars/Tars/Extensions/CommonVariables+Extension.swift
  Tars/Tars/Extensions/DashedCircle+Extension.swift
  Tars/Tars/SceneDelegate.swift
  Tars/Tars/View/CustomCircleView.swift
  Tars/Tars/ViewController/UniverseViewController.swift
Labels: 🧑‍💻오즈, fix

#8 [FEAT] selectedSquareView 구현
  Tars/Tars.xcodeproj/project.pbxproj
  Tars/Tars/View/CustomSquareView.swift
  Tars/Tars/ViewController/UniverseViewController.swift
Labels: 👩‍💻레나, 🪐 discovered

#16 [FEAT] 지평좌표계 x, y, z 좌표로 변환 구현
  Tars/Tars/Model/Body.swift
Labels: ✨feature, 👩‍💻제리

#15 [FEAT] infoView 구현
  Tars/Tars.xcodeproj/project.pbxproj
  Tars/Tars/Assets.xcassets/jupiter.imageset/Contents.json
  Tars/Tars/Assets.xcassets/jupiter.imageset/jupiter2.png
  Tars/Tars/Extensions/Label+Extension.swift
  Tars/Tars/SceneDelegate.swift
  Tars/Tars/ViewController/InfoViewController.swift
Labels: ✨feature, 👩‍💻에이든, 📚 info

#20 [HOTFIX] fix xcode missing files
  Tars/Tars.xcodeproj/project.pbxproj
Labels: 🧑‍💻오즈, 🛠fix

#23 [FIX] 지평 좌표계 x,y,z 변환 수정
  Tars/Tars/Model/Body.swift
Labels: 👩‍💻제리, 🛠fix

#21 [FEAT] 행성의 좌표를 이용해 배치하는 기능 구현 #4
  Tars/Tars.xcodeproj/project.pbxproj
  Tars/Tars/Assets.xcassets/planets/Contents.json
  Tars/Tars/Assets.xcassets/planets/jupiter.imageset/Contents.json
  Tars/Tars/Assets.xcassets/planets/jupiter.imageset/jpegPIA07782.width-1600.jpg
  Tars/Tars/Assets.xcassets/planets/mars.imageset/Contents.json
  Tars/Tars/Assets.xcassets/planets/mars.imageset/mars.jpg
  Tars/Tars/Assets.xcassets/planets/mercury.imageset/Contents.json
  Tars/Tars/Assets.xcassets/planets/mercury.imageset/mercury.jpg
  Tars/Tars/Assets.xcassets/planets/moon.imageset/Contents.json
  Tars/Tars/Assets.xcassets/planets/moon.imageset/moon-diffuse.jpg
  Tars/Tars/Assets.xcassets/planets/saturn.imageset/Contents.json
  Tars/Tars/Assets.xcassets/planets/saturn.imageset/saturn.jpg
  Tars/Tars/Assets.xcassets/planets/sun.imageset/Contents.json
  Tars/Tars/Assets.xcassets/planets/sun.imageset/sun-diffuse.jpg
  Tars/Tars/Assets.xcassets/planets/uranus.imageset/Contents.json
  Tars/Tars/Assets.xcassets/planets/uranus.imageset/uranusmap-10x5k-CC.jpg
  Tars/Tars/Assets.xcassets/planets/venus.imageset/2k_venus_surface.png
  Tars/Tars/Assets.xcassets/planets/venus.imageset/Contents.json
  Tars/Tars/UniverseBackground.scn
  Tars/Tars/View/CustomPlanetView.swift
  Tars/Tars/ViewController/UniverseViewController.swift
Labels: ✨feature, 🧑‍💻니로, 🧭 explore

#25 [HOTFIX] 불필요한 함수 제거
  Tars/Tars/ViewController/UniverseViewController.swift
Labels: 🧑‍💻니로, 🛠fix

#27 [HOTFIX] Fix degree to radian
  Tars/Tars.xcodeproj/project.pbxproj
  Tars/Tars/Extensions/Float+Extension.swift
  Tars/Tars/Model/Body.swift
Labels: 👩‍💻제리, 🛠fix

#29 [FEAT] ARkit view transform
  .gitignore
  Tars/Tars.xcodeproj/project.pbxproj
  Tars/Tars/Assets.xcassets/UniverseBackground/Contents.json
  Tars/Tars/Assets.xcassets/UniverseBackground/sky1.imageset/Contents.json
  Tars/Tars/Assets.xcassets/UniverseBackground/sky1.imageset/sky.jpg
  Tars/Tars/Assets.xcassets/UniverseBackground/sky2.imageset/Contents.json
  Tars/Tars/Assets.xcassets/UniverseBackground/sky2.imageset/sky.jpg
  Tars/Tars/Assets.xcassets/UniverseBackground/sky3.imageset/Contents.json
  Tars/Tars/Assets.xcassets/UniverseBackground/sky3.imageset/sky.jpg
  Tars/Tars/Assets.xcassets/UniverseBackground/sky4.imageset/Contents.json
  Tars/Tars/Assets.xcassets/UniverseBackground/sky4.imageset/sky.jpg
  Tars/Tars/Assets.xcassets/UniverseBackground/sky5.imageset/Contents.json
  Tars/Tars/Assets.xcassets/UniverseBackground/sky5.imageset/sky.jpg
  Tars/Tars/Assets.xcassets/UniverseBackground/sky6.imageset/Contents.json
  Tars/Tars/Assets.xcassets/UniverseBackground/sky6.imageset/sky.jpg
  Tars/Tars/Assets.xcassets/planets/Jupiter_Map.imageset/Contents.json
  Tars/Tars/Assets.xcassets/planets/Jupiter_Map.imageset/jpegPIA07782.width-1600.jpg
  Tars/Tars/Assets.xcassets/planets/Mars_Map.imageset/Contents.json
  Tars/Tars/Assets.xcassets/planets/Mars_Map.imageset/mars.jpg
  Tars/Tars/Assets.xcassets/planets/Mercury_Map.imageset/Contents.json
  Tars/Tars/Assets.xcassets/planets/Mercury_Map.imageset/mercury.jpg
  Tars/Tars/Assets.xcassets/planets/Moon_Map.imageset/Contents.json
  Tars/Tars/Assets.xcassets/planets/Moon_Map.imageset/moon-diffuse.jpg
  Tars/Tars/Assets.xcassets/planets/Neptune_Map.imageset/Contents.json
  Tars/Tars/Assets.xcassets/planets/Neptune_Map.imageset/NEP0VTT1-CC-10x5k.jpg
  Tars/Tars/Assets.xcassets/planets/Saturn_Map.imageset/Contents.json
  Tars/Tars/Assets.xcassets/planets/Saturn_Map.imageset/saturn.jpg
  Tars/Tars/Assets.xcassets/planets/Sun_Map.imageset/Contents.json
  Tars/Tars/Assets.xcassets/planets/Sun_Map.imageset/sun-diffuse.jpg
  Tars/Tars/Assets.xcassets/planets/Uranus_Map.imageset/Contents.json
  Tars/Tars/Assets.xcassets/planets/Uranus_Map.imageset/uranusmap-10x5k-CC.jpg
  Tars/Tars/Assets.xcassets/planets/Venus_Map.imageset/2k_venus_surface.png
  Tars/Tars/Assets.xcassets/planets/Venus_Map.imageset/Contents.json
  Tars/Tars/Assets.xcassets/planets/jupiter.imageset/Contents.json
  Tars/Tars/Assets.xcassets/planets/mars.imageset/Contents.json
  Tars/Tars/Assets.xcassets/planets/mercury.imageset/Contents.json
  Tars/Tars/Assets.xcassets/planets/moon.imageset/Contents.json
  Tars/Tars/Assets.xcassets/planets/saturn.imageset/Contents.json
  Tars/Tars/Assets.xcassets/planets/sun.imageset/Contents.json
  Tars/Tars/Assets.xcassets/planets/uranus.imageset/Contents.json
  Tars/Tars/Assets.xcassets/planets/venus.imageset/Contents.json
  Tars/Tars/Info.plist
  Tars/Tars/Model/Body.swift
  Tars/Tars/Network/Base/Keys.swift
  Tars/Tars/View/CustomPlanetView.swift
  Tars/Tars/ViewController/UniverseViewController.swift
Labels: ✨feature, 🧑‍💻니로, 🔍search, 🧭 explore, 🪐 discovered, 🛠fix
