Repository DeveloperAcademy-POSTECH/MacC-Team-TARS, pull requests merged in 2022-11, with the labels that each got.

#36 [Feat] SelectPlanetCollectionView
  Tars/Tars.xcodeproj/project.pbxproj
  Tars/Tars/Assets.xcassets/PlanetsImage/Contents.json
  Tars/Tars/Assets.xcassets/PlanetsImage/Jupiter.imageset/Contents.json
  Tars/Tars/Assets.xcassets/PlanetsImage/Jupiter.imageset/jupiter.png
  Tars/Tars/Assets.xcassets/PlanetsImage/Mars.imageset/Contents.json
  Tars/Tars/Assets.xcassets/PlanetsImage/Mars.imageset/mars.png
  Tars/Tars/Assets.xcassets/PlanetsImage/Mercury.imageset/Contents.json
  Tars/Tars/Assets.xcassets/PlanetsImage/Mercury.imageset/mercury.png
  Tars/Tars/Assets.xcassets/PlanetsImage/Moon.imageset/Contents.json
  Tars/Tars/Assets.xcassets/PlanetsImage/Moon.imageset/moon.png
  Tars/Tars/Assets.xcassets/PlanetsImage/Neptune.imageset/Contents.json
  Tars/Tars/Assets.xcassets/PlanetsImage/Neptune.imageset/neptune.png
  Tars/Tars/Assets.xcassets/PlanetsImage/Saturn.imageset/Contents.json
  Tars/Tars/Assets.xcassets/PlanetsImage/Saturn.imageset/saturn.png
  Tars/Tars/Assets.xcassets/PlanetsImage/Sun.imageset/Contents.json
  Tars/Tars/Assets.xcassets/PlanetsImage/Sun.imageset/sun.png
  Tars/Tars/Assets.xcassets/PlanetsImage/Uranus.imageset/Contents.json
  Tars/Tars/Assets.xcassets/PlanetsImage/Uranus.imageset/uranus.png
  Tars/Tars/Assets.xcassets/PlanetsImage/Venus.imageset/Contents.json
  Tars/Tars/Assets.xcassets/PlanetsImage/Venus.imageset/venus.png
  Tars/Tars/Assets.xcassets/PlanetsMap/Contents.json
  Tars/Tars/Assets.xcassets/PlanetsMap/Jupiter_Map.imageset/Contents.json
  Tars/Tars/Assets.xcassets/PlanetsMap/Jupiter_Map.imageset/jpegPIA07782.width-1600.jpg
  Tars/Tars/Assets.xcassets/PlanetsMap/Mars_Map.imageset/Contents.json
  Tars/Tars/Assets.xcassets/PlanetsMap/Mars_Map.imageset/mars.jpg
  Tars/Tars/Assets.xcassets/PlanetsMap/Mercury_Map.imageset/Contents.json
  Tars/Tars/Assets.xcassets/PlanetsMap/Mercury_Map.imageset/mercury.jpg
  Tars/Tars/Assets.xcassets/PlanetsMap/Moon_Map.imageset/Contents.json
  Tars/Tars/Assets.xcassets/PlanetsMap/Moon_Map.imageset/moon-diffuse.jpg
  Tars/Tars/Assets.xcassets/PlanetsMap/Neptune_Map.imageset/Contents.json
  Tars/Tars/Assets.xcassets/PlanetsMap/Neptune_Map.imageset/NEP0VTT1-CC-10x5k.jpg
  Tars/Tars/Assets.xcassets/PlanetsMap/Saturn_Map.imageset/Contents.json
  Tars/Tars/Assets.xcassets/PlanetsMap/Saturn_Map.imageset/saturn.jpg
  Tars/Tars/Assets.xcassets/PlanetsMap/Sun_Map.imageset/Contents.json
  Tars/Tars/Assets.xcassets/PlanetsMap/Sun_Map.imageset/sun-diffuse.jpg
  Tars/Tars/Assets.xcassets/PlanetsMap/Uranus_Map.imageset/Contents.json
  Tars/Tars/Assets.xcassets/PlanetsMap/Uranus_Map.imageset/uranusmap-10x5k-CC.jpg
  Tars/Tars/Assets.xcassets/PlanetsMap/Venus_Map.imageset/2k_venus_surface.png
  Tars/Tars/Assets.xcassets/PlanetsMap/Venus_Map.imageset/Contents.json
  Tars/Tars/Assets.xcassets/SelectPlanetCollectionView/BackgroundImage.imageset/Contents.json
  Tars/Tars/Assets.xcassets/SelectPlanetCollectionView/BackgroundImage.imageset/backgroundImage.pdf
  Tars/Tars/Assets.xcassets/SelectPlanetCollectionView/Contents.json
  Tars/Tars/Extensions/PlanetList+Extension.swift
  Tars/Tars/Model/Planet.swift
  Tars/Tars/SceneDelegate.swift
  Tars/Tars/ViewController/Cell/SelectPlanetCollectionViewCell.swift
  Tars/Tars/ViewController/ContentsViewController.swift
  Tars/Tars/ViewController/SelectPlanetViewController.swift
Labels: ✨feature, 👩‍💻콜리

#42 [FEAT] search view 구현
  Tars/Tars.xcodeproj/project.pbxproj
  Tars/Tars/Assets.xcassets/PlanetsImage/Sun.imageset/sun.png
  Tars/Tars/SearchView/SelectPlanetCollectionViewCell.swift
  Tars/Tars/SearchView/UniverseSearchViewController+DataSource.swift
  Tars/Tars/SearchView/UniverseSearchViewController+FlowLayoutDelegate.swift
  Tars/Tars/ViewController/UniverseSearchViewController.swift
Labels: ✨feature, 👩‍💻콜리, 🪐 discovered

#40 [FEAT] Localization & String enum
  Tars/Tars.xcodeproj/project.pbxproj
  Tars/Tars/Extensions/Localized.swift
  Tars/Tars/ViewController/InfoViewController.swift
  Tars/Tars/ko.lproj/LaunchScreen.strings
  Tars/en.lproj/Localizable.strings
  Tars/ko.lproj/Localizable.strings
Labels: ✨feature, 🧑‍💻오즈

#47 [FEAT] main view
  Tars/Tars.xcodeproj/project.pbxproj
  Tars/Tars/SearchView/UniverseSearchViewController+DataSource.swift
  Tars/Tars/ViewController/SelectPlanetViewController.swift
  Tars/Tars/ViewController/SettingViewController.swift
  Tars/Tars/ViewController/UniverseSearchViewController.swift
Labels: ✨feature, 👩‍💻콜리, 🔍search, 🧭 explore, 🛠fix

#56 [FEAT] AR kit Spatial audio 소리 증감 구현
  Tars/Tars/Jupiter.mp3
  Tars/Tars/Mars.mp3
  Tars/Tars/Mercury.mp3
  Tars/Tars/Moon.mp3
  Tars/Tars/Saturn.mp3
  Tars/Tars/Sun.mp3
  Tars/Tars/Uranus.mp3
  Tars/Tars/ViewController/UniverseSearchViewController.swift
  Tars/Tars/ViewController/UniverseViewController.swift
Labels: ✨feature, 🧑‍💻니로, 🧭 explore, 🪐 discovered, 🎧 Spatital Audio

#57 [FEAT] Onboarding overlay 구현
  Tars/Tars.xcodeproj/project.pbxproj
  Tars/Tars.xcodeproj/xcshareddata/xcschemes/Tars.xcscheme
  Tars/Tars/Extensions/Localized.swift
  Tars/Tars/View/CustomBackgroundOverlayView.swift
  Tars/Tars/View/CustomOnboardingOverlayView.swift
  Tars/Tars/ViewController/LaunchScreenViewController.swift
  Tars/Tars/ViewController/OnboardingViewController.swift
  Tars/Tars/ViewController/UniverseSearchViewController.swift
  Tars/en.lproj/Localizable.strings
Labels: ✨feature, 🧑‍💻오즈, 🗣VoiceOver

#64 [FEAT] 행성이 선택되어 있는 상황에서 다른 행성을 선택시 소리가 안들리는 문제 해결
  Tars/Tars/ViewController/UniverseSearchViewController.swift
Labels: ✨feature, 🧑‍💻니로, 🪐 discovered, 🎧 Spatital Audio

#71 [FEAT] tap gesture & infoViewController
  Tars/Tars.xcodeproj/project.pbxproj
  Tars/Tars/Extensions/PlanetList+Extension.swift
  Tars/Tars/Model/Planet.swift
  Tars/Tars/SearchView/UniverseSearchViewController+DataSource.swift
  Tars/Tars/ViewController/ContentsViewController.swift
  Tars/Tars/ViewController/InfoViewController.swift
  Tars/Tars/ViewController/SettingViewController.swift
  Tars/Tars/ViewController/UniverseSearchViewController.swift
  Tars/Tars/ViewController/UniverseViewController.swift
Labels: ✨feature, 👩‍💻콜리, 📚 info, 🛠fix

#72 [FEAT] 권한허용 체크 기능 구현 (#58)
  Tars/Tars/ViewController/UniverseSearchViewController.swift
Labels: ✨feature, 👩‍💻레나

#73 [FEAT] 컴포넌트와 행성탐지 시 VoiceOver 기능 구현
  Tars/Tars/SearchView/UniverseSearchViewController+DataSource.swift
  Tars/Tars/ViewController/InfoViewController.swift
  Tars/Tars/ViewController/UniverseSearchViewController.swift
Labels: ✨feature, 👩‍💻소니, 🗣VoiceOver

#77 [FEAT] 행성이 탐지되었을 때 haptic feedback 적용
  Tars/Tars.xcodeproj/project.pbxproj
  Tars/Tars/Haptic/HapticManager.swift
  Tars/Tars/ViewController/UniverseSearchViewController.swift
Labels: ✨feature, 👩‍💻소니, 🪐 discovered

#79 [FEAT] launchscreen 수정
  Tars/Tars/Assets.xcassets/LaunchScreen/Contents.json
  Tars/Tars/Assets.xcassets/LaunchScreen/airpods.imageset/Contents.json
  Tars/Tars/Assets.xcassets/LaunchScreen/airpods.imageset/airpods.png
  Tars/Tars/Extensions/Color+Extension.swift
  Tars/Tars/Extensions/Localized.swift
  Tars/Tars/ViewController/LaunchScreenViewController.swift
  Tars/en.lproj/Localizable.strings
Labels: ✨feature, 🧑‍💻오즈

#82 [RELEASE] 5차 회의용 테스트플라이트 업데이트
  Tars/Tars/ViewController/UniverseSearchViewController.swift
Labels: 🌕release

#86 [Feat] InfoView 컨텐츠 및 천체 음악 재생 기능 구현
  Tars/Tars.xcodeproj/project.pbxproj
  Tars/Tars/Extensions/PlanetList+Extension.swift
  Tars/Tars/Model/PlanetContent.swift
  Tars/Tars/SoundManager/SoundManager.swift
  Tars/Tars/View/CustomPlanetInfoView.swift
  Tars/Tars/ViewController/InfoViewController.swift
  Tars/Tars/ViewController/UniverseSearchViewController.swift
Labels: 👩‍💻레나, 📚 info

#89 [RELEASE]Testflight ver 3
  Tars/Tars/Assets.xcassets/AppIcon.appiconset/114.png
  Tars/Tars/Assets.xcassets/AppIcon.appiconset/120.png
  Tars/Tars/Assets.xcassets/AppIcon.appiconset/180.png
  Tars/Tars/Assets.xcassets/AppIcon.appiconset/29.png
  Tars/Tars/Assets.xcassets/AppIcon.appiconset/40.png
  Tars/Tars/Assets.xcassets/AppIcon.appiconset/57.png
  Tars/Tars/Assets.xcassets/AppIcon.appiconset/58.png
  Tars/Tars/Assets.xcassets/AppIcon.appiconset/60.png
  Tars/Tars/Assets.xcassets/AppIcon.appiconset/80.png
  Tars/Tars/Assets.xcassets/AppIcon.appiconset/87.png
  Tars/Tars/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: 🌕release

#92 [FEAT] Localization
  Tars/Tars.xcodeproj/project.pbxproj
  Tars/Tars/Extensions/Localized.swift
  Tars/Tars/Extensions/PlanetList+Extension.swift
  Tars/Tars/Info.plist
  Tars/Tars/Location/LocationManagerDelegate.swift
  Tars/Tars/SearchView/UniverseSearchViewController+DataSource.swift
  Tars/Tars/View/CustomPlanetInfoView.swift
  Tars/Tars/View/CustomSquareView.swift
  Tars/Tars/ViewController/InfoViewController.swift
  Tars/Tars/ViewController/UniverseSearchViewController.swift
  Tars/en.lproj/InfoPlist.strings
  Tars/en.lproj/Localizable.strings
  Tars/ko.lproj/InfoPlist.strings
Labels: 📚 info, 🗣VoiceOver
