Repository DeveloperAcademy-POSTECH/MacC-Team-TARS, pull requests merged in 2024-09, with the labels that each got.

#123 [REFACTOR] 행성 감지시 VoiceOver 언어 설정 및 감지음 추가 및 NavigationTitle 수정
  Tars/Tars/Manager/SoundManager/SoundManager.swift
  Tars/Tars/View/UniverseSearch/ViewController/UniverseMainViewController.swift
  Tars/Tars/ViewModel/UniverseModeViewModel.swift
Labels: 🧑‍💻니로, 🗣VoiceOver, 🛠️refactor

#126 [REFACTOR] playAudio 메서드의 잘못된 매개변수 변경
  Tars/Tars/Manager/SoundManager/SoundManager.swift
  Tars/Tars/View/InfoView/InfoViewController.swift
Labels: 🧑‍💻니로, 🛠️refactor

#128 [FIX] Onboarding 레이아웃 수정, LaunchScreen 화면전환 수정, API 호출 이후 Onboarding 사라지도록 구현
  Tars/Tars/View/InfoView/InfoViewController.swift
  Tars/Tars/View/LauchScreen/ViewController/LaunchScreenViewController.swift
  Tars/Tars/View/LauchScreen/ViewController/OnboardingView.swift
  Tars/Tars/View/UniverseSearch/ViewController/UniverseMainViewController.swift
  Tars/Tars/ViewModel/UniverseLocationViewModel.swift
Labels: 👩‍💻레나, 🛠fix
