Repository DeveloperAcademy-POSTECH/MacC-Team-TARS, pull requests merged in 2024-07, with the labels that each got.

#108 [REFACTOR] Localization 구조 수정 및 Constants 설정
  Tars/InfoPlist.xcstrings
  Tars/Tars.xcodeproj/project.pbxproj
  Tars/Tars/Global/Constants/AudioConstants.swift
  Tars/Tars/Global/Constants/PlanetConstants.swift
  Tars/Tars/Global/Constants/ResourceConstants.swift
  Tars/Tars/Global/Extensions/Color+Extension.swift
  Tars/Tars/Global/Extensions/Localized.swift
  Tars/Tars/Global/Extensions/PlanetList+Extension.swift
  Tars/Tars/Global/Extensions/String+Extension.swift
  Tars/Tars/Global/Localization/Localizable.xcstrings
  Tars/Tars/Global/Localization/LocalizableKeys.swift
  Tars/Tars/Network/APIService/BodiesPositionsResponse.swift
  Tars/Tars/Network/Location/LocationManagerDelegate.swift
  Tars/Tars/Network/Manager/HapticManager/HapticManager.swift
  Tars/Tars/Network/Manager/PlanetManager.swift
  Tars/Tars/Network/Manager/SoundManager/SoundManager.swift
  Tars/Tars/Network/Model/Planet.swift
  Tars/Tars/Network/Model/PlanetContent.swift
  Tars/Tars/Screens/InfoView/CustomPlanetInfoView.swift
  Tars/Tars/Screens/InfoView/InfoViewController.swift
  Tars/Tars/Screens/LauchScreen/View/CustomOnboardingOverlayView.swift
  Tars/Tars/Screens/LauchScreen/ViewController/LaunchScreenViewController.swift
  Tars/Tars/Screens/UniverseSearch/Cells/SelectPlanetCollectionViewCell.swift
  Tars/Tars/Screens/UniverseSearch/UniverseSearchViewController+DataSource.swift
  Tars/Tars/Screens/UniverseSearch/ViewController/UniverseSearchViewController.swift
  Tars/en.lproj/InfoPlist.strings
  Tars/en.lproj/Localizable.strings
  Tars/ko.lproj/InfoPlist.strings
  Tars/ko.lproj/Localizable.strings
Labels: 👩‍💻레나, 🛠️refactor

#109 [Refactor] UniverseSearchViewController UI 코드 리펙토링
  Tars/Tars.xcodeproj/project.pbxproj
  Tars/Tars.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Tars/Tars/Global/Extensions/View+Extension.swift
  Tars/Tars/Screens/UniverseSearch/UniverseSearchViewController+DataSource.swift
  Tars/Tars/Screens/UniverseSearch/UniverseSearchViewController+FlowLayoutDelegate.swift
  Tars/Tars/Screens/UniverseSearch/ViewController/UniverseMainViewController.swift
Labels: 🧑‍💻니로, 🛠️refactor

#112 [BUG] UniverseSearchVC 실행을 위한 버그 수정
  Tars/Tars.xcodeproj/project.pbxproj
  Tars/Tars.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Tars/Tars/Screens/UniverseSearch/Collection/UniverseMainViewController+FlowLayoutDelegate.swift
  Tars/Tars/Screens/UniverseSearch/Collection/UniverseMainViewControllerUniverseMainViewController.swift
  Tars/Tars/Screens/UniverseSearch/Collection/UniverseSearch/UniverseSearchViewController+DataSource.swift
  Tars/Tars/Screens/UniverseSearch/Collection/UniverseSearch/UniverseSearchViewController+FlowLayoutDelegate.swift
  Tars/Tars/Screens/UniverseSearch/ViewController/UniverseMainViewController.swift
Labels: 🐛debug, 🧑‍💻니로
