Repository DeveloperAcademy-POSTECH/MacC-Team-TARS, pull requests merged in 2024-08, with the labels that each got.

#116 [REFACTOR] DRAFT_LocationViewModel 구현 및 관련 사항 리팩토링
  Tars/Tars.xcodeproj/project.pbxproj
  Tars/Tars.xcodeproj/xcuserdata/lena.xcuserdatad/xcschemes/xcschememanagement.plist
  Tars/Tars/Global/Extensions/CALayer+Extension.swift
  Tars/Tars/Global/Extensions/Label+Extension.swift
  Tars/Tars/Manager/HapticManager/HapticManager.swift
  Tars/Tars/Manager/LocationManager/LocationManager.swift
  Tars/Tars/Manager/LocationManager/LocationManagerDelegate.swift
  Tars/Tars/Manager/PlanetManager.swift
  Tars/Tars/Manager/SoundManager/SoundManager.swift
  Tars/Tars/Model/PlanetInfo.swift
  Tars/Tars/Network/Location/LocationManager.swift
  Tars/Tars/Screens/InfoView/InfoViewController.swift
  Tars/Tars/Screens/LauchScreen/ViewController/LaunchScreenViewController.swift
  Tars/Tars/Screens/Setting/SettingViewController.swift
  Tars/Tars/Screens/UniverseSearch/Collection/UniverseMainViewControllerUniverseMainViewController.swift
  Tars/Tars/View/InfoView/CustomPlanetInfoView.swift
  Tars/Tars/View/InfoView/InfoViewController.swift
  Tars/Tars/View/LauchScreen/View/CustomBackgroundOverlayView.swift
  Tars/Tars/View/LauchScreen/View/CustomOnboardingOverlayView.swift
  Tars/Tars/View/LauchScreen/ViewController/LaunchScreenViewController.swift
  Tars/Tars/View/LauchScreen/ViewController/OnboardingView.swift
  Tars/Tars/View/UniverseSearch/Cells/SelectPlanetCollectionViewCell.swift
  Tars/Tars/View/UniverseSearch/Cells/SelectPlanetMainCollectionViewCell.swift
  Tars/Tars/View/UniverseSearch/Collection/UniverseMainViewController+FlowLayoutDelegate.swift
  Tars/Tars/View/UniverseSearch/Collection/UniverseMainViewControllerUniverseMainViewController.swift
  Tars/Tars/View/UniverseSearch/Collection/UniverseSearch/UniverseSearchViewController+DataSource.swift
  Tars/Tars/View/UniverseSearch/Collection/UniverseSearch/UniverseSearchViewController+FlowLayoutDelegate.swift
  Tars/Tars/View/UniverseSearch/ViewController/UniverseMainViewController.swift
  Tars/Tars/View/UniverseSearch/ViewController/UniverseSearchViewController.swift
  Tars/Tars/ViewModel/UniverseLocationViewModel.swift
Labels: 👩‍💻레나, 🔭 API, 🛠️refactor

#117 [REFACTOR] UniverseModeViewModel 구현 및 SceneKitAudioVolumeManager 구현
  Tars/Tars.xcodeproj/project.pbxproj
  Tars/Tars/Model/Cardinal.swift
  Tars/Tars/Model/Mode.swift
  Tars/Tars/Model/PlanetInfo.swift
  Tars/Tars/SceneKitAudioPlayer.swift
  Tars/Tars/View/UniverseSearch/Collection/UniverseMainViewController+DataSource.swift
  Tars/Tars/View/UniverseSearch/ViewController/UniverseMainViewController.swift
  Tars/Tars/ViewModel/UniverseModeViewModel.swift
Labels: ✨feature, 🧑‍💻니로

#120 [BUB] Detected 된 행성 음향 조절 코드 추가
  Tars/Tars/SceneKitAudioPlayer.swift
  Tars/Tars/View/UniverseSearch/ViewController/UniverseMainViewController.swift
Labels: 🐛debug, 🧑‍💻니로
